import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-teal-500 p-2 px-5 flex gap-5">
          <Link href={"/dashboard"}>Dashboard</Link>
          <Link href={"/blog"}>Blog</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
